### ISSUE TITLE
Memento sometimes doesn't return call data

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/memento#136]
#### Symptoms

The Memento live tests failed with:

```
Memento - Basic Call (TCP) - (6505550020, 6505550085) Failed
Endpoint threw exception:
 - undefined method `from_uri' for nil:NilClass
   - /home/ubuntu/clearwater-live-test/lib/tests/memento.rb:64:in `check_users_call_list'
   - /home/ubuntu/clearwater-live-test/lib/tests/memento.rb:158:in `block (2 levels) in <top (required)>'
```

From a code read of the tests, it looks like the `<calls>` element might have been unexpectedly empty.

SAS shows that the call went through, and we have the right Memento logs ("Recording the start of a call", "Recording the end of a call" twice each).

#### Impact

The Clearwater live tests are less stable.

Users may not get their correct call lists.

#### Release and environment 

Farfetch'd release (release-99 tag), on EC2.

#### Steps to reproduce

No good repro scenario - happens intermittently when running the Memento live tests.

**Comment by graemerobertson** [comment]
I don't believe we ever see this on deployments with a single Memento - possibly this is only exposed when we have a Memento cluster.

Also it's worth noting that this could easily be a bug in the live test scripts themselves.

**Comment by rkd-msw** [comment]
Low priority, as it's an Memento issue, and Memento isn't production-ready.

**Comment by rkd-msw** [comment]
My new diagnostics have come into play, showing that the XML is completely empty:

```
Memento - Basic Call (TCP) - (6505550087, 6505550071) Failed
Endpoint threw exception:
 - No calls in call record - original XML was:
   - /home/ubuntu/clearwater-live-test/lib/tests/memento.rb:56:in `check_users_call_list'
   - /home/ubuntu/clearwater-live-test/lib/tests/memento.rb:177:in `block (2 levels) in <top (required)>'
```

**Comment by rkd-msw** [comment]
Corresponding bit of the logs:

```
26-07-2016 15:50:21.119 UTC Debug httpdigestauthenticate.cpp:473: Authentication accepted
26-07-2016 15:50:21.119 UTC Debug cassandra_store.cpp:284: Getting thread-local Client
26-07-2016 15:50:21.119 UTC Debug cassandra_store.cpp:289: No thread-local Client - creating one
26-07-2016 15:50:21.119 UTC Debug statistic.cpp:103: Send new value for statistic auth_successes, size 1
26-07-2016 15:50:21.119 UTC Debug zmq_lvc.cpp:172: Update to auth_successes statistic
26-07-2016 15:50:21.119 UTC Debug zmq_lvc.cpp:256: Clearing message cache for 0x7f9b1401c730
26-07-2016 15:50:21.119 UTC Debug call_list_store.cpp:256: Get call fragments for IMPU: 'sip:6505550071@cw-ngv.com'
26-07-2016 15:50:21.205 UTC Debug call_list_store.cpp:306: Retrieved 1 call fragments from the store
26-07-2016 15:50:21.205 UTC Debug communicationmonitor.cpp:82: Checking communication changes - successful attempts 1, failures 0
26-07-2016 15:50:21.205 UTC Debug alarm.cpp:417: AlarmReqAgent: servicing request queue
26-07-2016 15:50:21.205 UTC Status alarm.cpp:62: memento issued 5005.1 alarm
26-07-2016 15:50:21.206 UTC Debug statistic.cpp:103: Send new value for statistic cassandra_read_latency, size 5
26-07-2016 15:50:21.206 UTC Warning call_list_xml.cpp:85: Only one entry for call record 20160726155019_3923904689531256833 but it was not REJECTED
26-07-2016 15:50:21.206 UTC Debug statistic.cpp:103: Send new value for statistic record_size, size 5
26-07-2016 15:50:21.206 UTC Debug statistic.cpp:103: Send new value for statistic record_length, size 5
26-07-2016 15:50:21.206 UTC Verbose httpstack.cpp:69: Sending response 200 to request for URL /org.projectclearwater.call-list/users/sip:6505550071@cw-ngv.com/call-list.xml, args (null)
```

**Comment by rkd-msw** [comment]
The problem here is that the 'end' fragment of the call has gone missing. SAS says so:

```
Did not process invalid call record.

Call record ID 3923904689531256833, start timestamp 20160726155019

Single record fragment of type begin, expected 'rejected'
```

**Comment by rkd-msw** [comment]
The bug is that:

* we write the Cassandra data asynchronously (https://github.com/Metaswitch/memento-as/blob/master/src/call_list_store_processor.cpp#L98)
* Cassandra writes are particularly slow - 300ms+ (see log below)
* we're trying to read the data over HTTP before it has been successfully written - and in fact now that I know what I'm looking for, this is obvious from SAS, because the HTTP logs are at 15:50:21.206 but in the call's SAS trace, the 'Call list fragment was successfully written to Cassandra' log doesn't appear at  15:50:21.285

```
26-07-2016 15:50:21.285 UTC Debug call_list_store_processor.cpp:170: Request latency = 354720us
26-07-2016 15:50:21.285 UTC Debug alarm.cpp:417: AlarmReqAgent: servicing request queue
26-07-2016 15:50:21.285 UTC Debug statistic.cpp:103: Send new value for statistic memento_cassandra_write_latency, size 5
26-07-2016 15:50:21.285 UTC Debug statistic.cpp:103: Send new value for statistic memento_completed_calls, size 1
26-07-2016 15:50:21.285 UTC Debug zmq_lvc.cpp:172: Update to memento_completed_calls statistic
26-07-2016 15:50:21.285 UTC Debug zmq_lvc.cpp:256: Clearing message cache for 0x7ff96c062120
26-07-2016 15:50:21.285 UTC Debug zmq_lvc.cpp:172: Update to memento_cassandra_write_latency statistic
26-07-2016 15:50:21.285 UTC Debug zmq_lvc.cpp:256: Clearing message cache for 0x7ff96c074a50
26-07-2016 15:50:21.285 UTC Debug call_list_store_processor.cpp:170: Request latency = 355556us
```
